name: Deploy to AWS EC2

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Build Docker image
      run: docker build -t nodejs-hello-node .

    - name: Save Docker image to file
      run: docker save -o nodejs-hello-node.tar nodejs-hello-node

    - name: Copy Docker image to EC2
      run: scp -o StrictHostKeyChecking=no nodejs-hello-node.tar ec2-user@${{ secrets.EC2_PUBLIC_IP }}:~/nodejs-hello-node.tar

    - name: Deploy Docker container on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
        docker load -i ~/nodejs-hello-node.tar
        docker run -d -p 80:3000 nodejs-hello-node
        EOF
